version: '3.8'

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    environment:
      - RASA_MODEL_SERVER=${RASA_MODEL_SERVER}
      - RASA_MODEL_TOKEN=${RASA_MODEL_TOKEN}
      - RASA_DB_URL=${RASA_DB_URL}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    volumes:
      - ./models:/app/models
    depends_on:
      - actions
      - redis
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  actions:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    environment:
      - RASA_DB_URL=${RASA_DB_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  redis_data:
  rabbitmq_data: